name: Build README and update data

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Update README and data
        run: |-
          python update.py
      - name: Commit and push if files changed
        run: |-
          git diff
          git config --global user.email "bot@example.com"
          git config --global user.name "bot"
          git diff --quiet || (git add README.md data.csv data.json && git commit -m "update readme and data")
          git push
